site_name: Arduino Documentation
theme: readthedocs
docs_dir: 'doc'
#nav:
pages:
    - 'Home': 'index.md'
    - 'Syntax': 'Syntax/syntax.md'
    - 'Data Types': 'Data_Types/data_types.md'
    - 'Core Functions': 'Builtin/builtin.md'
    - 'Math': 'Math/math.md'
    - 'Time': 'Time/time.md'
    - 'Interrupts': 'Interrupts/interrupts.md'
    - 'Random': 'Random/random.md'
    - 'Serial Monitor': 'Serial/Serial_Monitor.md'
    - 'Libraries':
        - 'Servo': 'Libraries/servo.md'
    - 'Third Party Libraries':
        - 'DHT': 'Libraries/dht.md'
        - 'LCD': 'Libraries/liquid_crystal.md'
        - 'Keypad': 'Libraries/keypad.md'
extra_css:
    - css/doc.css
